# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-19 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('email', models.EmailField(max_length=60, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('pnumber', models.IntegerField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('hobby', models.CharField(max_length=30)),
                ('profilepic', models.FileField(upload_to='')),
                ('password', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'signup',
            },
        ),
    ]
