# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-22 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='pnumber',
            field=models.IntegerField(),
        ),
    ]
