# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-29 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20200222_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='location',
            field=models.CharField(default='Nairobi/Kenya', max_length=30),
        ),
    ]
