# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11.23 on 2020-03-05 04:05
=======
# Generated by Django 1.11.23 on 2020-03-02 12:25
>>>>>>> upstream/master
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('signup', '0001_initial'),
=======
        ('signup', '0003_auto_20200229_2121'),
>>>>>>> upstream/master
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=50)),
                ('event_description', models.TextField(max_length=500)),
<<<<<<< HEAD
                ('post_time', models.TimeField(auto_now_add=True)),
                ('event_brief_pic', models.FileField(upload_to='')),
=======
                ('event_brief_pic', models.ImageField(upload_to='')),
>>>>>>> upstream/master
                ('usereventid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='signup.signup')),
            ],
            options={
                'db_table': 'events',
            },
        ),
    ]
