# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-02 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signup', '0003_auto_20200229_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=50)),
                ('event_description', models.TextField(max_length=500)),
                ('event_brief_pic', models.ImageField(upload_to='')),
                ('usereventid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='signup.signup')),
            ],
            options={
                'db_table': 'events',
            },
        ),
    ]
