# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-02 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_brief_pic',
            field=models.FileField(upload_to=''),
        ),
    ]
