# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-19 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sell_goods',
            fields=[
                ('itemid', models.AutoField(primary_key=True, serialize=False)),
                ('itemdesc', models.CharField(max_length=255)),
                ('price', models.FloatField(max_length=10)),
                ('itemimg', models.FileField(upload_to='')),
            ],
        ),
    ]
