# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-05 04:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='groups',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('gicon', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='membersdb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupId', to='groups.groups')),
                ('gmemberId', models.ManyToManyField(related_name='member', to='signup.signup')),
            ],
            options={
                'db_table': 'groupmemebers',
            },
        ),
    ]
