# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-05 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
        ('groups', '0002_auto_20200305_0418'),
    ]

    operations = [
        migrations.CreateModel(
            name='members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupid', models.ManyToManyField(to='groups.groups')),
                ('memberuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.signup')),
            ],
        ),
        migrations.RemoveField(
            model_name='membersdb',
            name='gid',
        ),
        migrations.RemoveField(
            model_name='membersdb',
            name='gmemberId',
        ),
        migrations.DeleteModel(
            name='membersdb',
        ),
    ]
