# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-05 04:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20200305_0422'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='members',
            table='members',
        ),
    ]
