# Generated by Django 3.0.3 on 2020-03-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_auto_20200307_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='groupid',
            field=models.ManyToManyField(related_name='gbridge', to='groups.groups'),
        ),
    ]
