# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-22 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signup', '0002_auto_20200222_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='signup.signup')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='signup.signup')),
            ],
        ),
    ]
