# Generated by Django 3.0 on 2020-03-07 20:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followers',
            name='test',
            field=models.CharField(default=django.utils.timezone.now, max_length=34),
            preserve_default=False,
        ),
    ]
