# Generated by Django 3.0 on 2020-03-07 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0002_followers_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='test',
        ),
    ]
