# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-22 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0002_auto_20200222_1818'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='followers',
            table='Followers',
        ),
    ]
