# Generated by Django 3.0 on 2020-03-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0003_remove_followers_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='is_following',
            field=models.BooleanField(default=False),
        ),
    ]
