# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11.23 on 2020-03-05 04:05
=======
# Generated by Django 1.11.23 on 2020-03-03 12:04
>>>>>>> upstream/master
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
