# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-05 05:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notif',
            table='notifications',
        ),
    ]
